name: 📦 Publish Controllers

on:
  push:
    branches:
      - main
    paths:
      - 'apps/controllers/package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: setup mongodb
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: 6.0

      - name: install dependencies
        run: pnpm install --no-link-workspace-packages --no-frozen-lockfile

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test:controllers
  publish-controllers:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check_version
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD -- 'apps/controllers/package.json' | grep '"version":' || true)
          if [ -z "$VERSION_CHANGED" ]; then
            echo "Version has not changed. Skipping..."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Version has changed. Running job..."
            echo "skip=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: setup node
        if: ${{ env.skip == 'false' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: setup pnpm
        if: ${{ env.skip == 'false' }}
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install dependencies
        if: ${{ env.skip == 'false' }}
        run: pnpm install --no-link-workspace-packages --no-frozen-lockfile

      - name: build
        if: ${{ env.skip == 'false' }}
        run: pnpm build:controllers

      - name: registry
        if: ${{ env.skip == 'false' }}
        run: npm set registry=https://registry.npmjs.org/

      - name: publish
        if: ${{ env.skip == 'false' }}
        run: |
          cd apps/controllers
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
